on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tag:
        required: true
        type: string
      path:
        required: true
        type: string

jobs:
  update-kustomize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ArgoCD Repo
        uses: actions/checkout@v4
        with:
          repository: user/argocd
          token: ${{ secrets.DEPLOYMENT_TOKEN }}

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Update Image Tag
        run: |
          cd ${{ inputs.path }}
          kustomize edit set image "${{ inputs.image_name }}=*:${{ inputs.tag }}"
        # kustomize edit set image ${{ inputs.image_name }}=ghcr.io/${{ github.repository_owner }}/${{ inputs.image_name }}:${{ inputs.tag }}
          
      - name: Commit and Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "deploy: update ${{ inputs.image_name }} to ${{ inputs.tag }} in ${{ inputs.path }}"
          git push
